version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=cs6400
      - MYSQL_DATABASE=cs6400groupproject
      - MYSQL_USER=cs6400
      - MYSQL_PASSWORD=cs6400
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/cs6400groupproject?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=cs6400
      - SPRING_DATASOURCE_PASSWORD=cs6400
    ports:
      - "8080:8080"

volumes:
  db_data: